version: "3.8"

services:
  backend:
    depends_on:
      - db
    image: be-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/app/backend
    ports:
      - 8000:8000
    container_name: be-dev
    environment:
      - ./backend/.env
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  db:
    container_name: postgresql
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    image: fe-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    container_name: fe-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    ports:
      - 8080:80
    container_name: reverse-proxy

volumes:
  postgres-data:
  node-modules:
